apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: <Password>

# echo -n 'myrootpassword' | openssl base64     =>     (The Output from this command is the <Password> but in encrepted format)
